# Generated by Django 4.2.7 on 2023-11-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0002_key_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
