# Generated by Django 4.2.7 on 2023-11-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0004_adress_person_address_alter_key_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='owner',
        ),
    ]
