# Generated by Django 4.2.7 on 2023-11-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('key_manager', '0006_remove_person_address_alter_key_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.adress'),
        ),
    ]
