# Generated by Django 4.2.7 on 2023-11-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0007_alter_key_address'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
    ]
