# Generated by Django 4.2.7 on 2023-11-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_adress_address_remove_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.address'),
        ),
    ]
